title: Weavercast
description: "A podcast about graphic novels."
author:
  name: "SRWeaver"
  email: "lwflouisa@gmail.com"
  url: "lwflouisa.github.io/Weavercast"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SRWeaver"
year : "2020"
